---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo Hello
        run: |             # Aquí también debe haber un espacio después de los dos puntos
          echo hello world